package main

import (
	"fmt"
	"io"
	"strings"
)

func pct(n, d int) string {
	if d == 0 {
		return "-"
	}
	return fmt.Sprintf("%.1f%%", 100*float64(n)/float64(d))
}

// summary prints each class's totals.
func summary(w io.Writer, rep *Report) {
	for _, c := range rep.Classes {
		fmt.Fprintf(w, "%-15s %5d of %5d read (%s)\n", c.Name, c.Passed, c.Total, pct(c.Passed, c.Total))
		for _, l := range c.Locations {
			fmt.Fprintf(w, "    %-28s %5d of %5d\n", l.Path, l.Passed, l.Total)
		}
	}
	z := rep.Zones
	fmt.Fprintf(w, "zones           %d declared", z.Declared)
	for _, k := range z.Kinds {
		fmt.Fprintf(w, ", %d %s", k.Declared, k.Kind)
	}
	fmt.Fprintf(w, "; %d missing\n", len(z.Missing))
	o := z.Outdoor
	fmt.Fprintf(w, "outdoor zones   %d dry-run: terrain %d, clean %d; placements %d of %d convert (%s)\n",
		o.Zones, o.Terrain, o.Clean, o.Converting, o.Placements, pct(o.Converting, o.Placements))
}

// markdown renders the report for reading. It is generated, like the JSON,
// and says so.
func markdown(rep *Report) string {
	var b strings.Builder
	p := func(format string, a ...any) { fmt.Fprintf(&b, format, a...) }

	p("# Asset census\n\n")
	p("Generated by `go run ./cmd/census` from an installed copy of the game; do not edit by hand.\n")
	p("It counts what this project's readers and converters can handle. It holds file names, counts and causes only.\n\n")

	p("## Summary\n\n")
	p("| Class | Read | Total | Rate |\n|---|---:|---:|---:|\n")
	for _, c := range rep.Classes {
		p("| %s | %d | %d | %s |\n", c.Name, c.Passed, c.Total, pct(c.Passed, c.Total))
	}
	o := rep.Zones.Outdoor
	p("| outdoor placements | %d | %d | %s |\n\n", o.Converting, o.Placements, pct(o.Converting, o.Placements))

	p("## Read, not drawn\n\n")
	p("A model counts as read when every block in it parses. Some blocks are read exactly but not rendered; ")
	p("the models carrying them draw, without that feature. Files carrying each:\n\n")
	p("| Class | Feature | Files |\n|---|---|---:|\n")
	for _, c := range rep.Classes {
		for _, f := range c.ReadNotDrawn {
			p("| %s | %s | %d |\n", c.Name, f.Feature, f.Files)
		}
	}
	p("\nParticle gravity is drawn, approximated for point gravity as it acts at the emitter. ")
	p("Textures stored inside models are decoded and written like any other.\n\n")

	for _, c := range rep.Classes {
		p("## %s\n\n%s.\n\n", strings.ToUpper(c.Name[:1])+c.Name[1:], strings.ToUpper(c.What[:1])+c.What[1:])
		p("| Location | Read | Total |\n|---|---:|---:|\n")
		for _, l := range c.Locations {
			p("| `%s` | %d | %d |\n", l.Path, l.Passed, l.Total)
		}
		p("\n")
		if len(c.Failures) == 0 {
			p("No failures.\n\n")
			continue
		}
		p("| Cause | Count | Examples |\n|---|---:|---|\n")
		for _, f := range c.Failures {
			p("| %s | %d | %s |\n", f.Cause, f.Count, strings.Join(f.Examples, ", "))
		}
		p("\n")
	}

	z := rep.Zones
	p("## Zones\n\n")
	p("`zones.dat` declares %d zones.\n\n", z.Declared)
	p("| Type | Declared | Present | Type line missing |\n|---|---:|---:|---:|\n")
	for _, k := range z.Kinds {
		p("| %s | %d | %d | %d |\n", k.Kind, k.Declared, k.Present, k.Untyped)
	}
	p("\nA zone with no type line is counted as outdoor: its folder holds the same terrain and scenery archives.\n\n")
	if len(z.Missing) > 0 {
		p("Declared but without a folder in this install:\n\n")
		for _, m := range z.Missing {
			p("- %03d %s (%s)\n", m.Num, m.Name, m.Kind)
		}
		p("\n")
	}

	p("### Outdoor zones\n\n")
	p("Each outdoor zone is dry-run: terrain read, and every model its fixtures place baked in memory. ")
	p("%d zones; terrain reads in %d; %d convert completely. ", o.Zones, o.Terrain, o.Clean)
	p("%d of %d placements convert (%s), from %d of %d distinct models.\n\n",
		o.Converting, o.Placements, pct(o.Converting, o.Placements), o.ModelsBaked, o.ModelsTried)
	p("| Zone | Name | Terrain | Placements | Converting | Failing models |\n|---:|---|---|---:|---:|---|\n")
	for _, r := range z.Rows {
		var fails []string
		for i, f := range r.Failing {
			if i == maxExamples {
				fails = append(fails, fmt.Sprintf("and %d more", len(r.Failing)-i))
				break
			}
			fails = append(fails, fmt.Sprintf("%s (%d, %s)", f.File, f.Placements, f.Cause))
		}
		if r.Scenery != "" {
			fails = append([]string{"scenery tables: " + r.Scenery}, fails...)
		}
		name := r.Name
		if r.Frontier {
			name += " (frontier)"
		}
		p("| %03d | %s | %s | %d | %d | %s |\n", r.Num, name, r.Terrain, r.Placements, r.Converting, strings.Join(fails, "; "))
	}
	return b.String()
}
